name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up pnpm
        run: |
          corepack enable
          pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Tests
        run: pnpm run test

      - name: Rules check
        run: pnpm run rules:check:ci
