name: Docs Validation
on:
  pull_request:
    paths:
      - "docs/"
      - "builder/"
      - ".github/workflows/docs.yml"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10.15.1 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "pnpm" }
      - name: Install deps
        run: pnpm install --frozen-lockfile=false
      - name: Docs guardrails
        run: |
          pnpm run docs:all || true
      - name: Schema check
        run: |
          python -m pip install pyyaml
          python builder/evaluators/doc_schema.py || true
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: docs-reports
          path: |
            builder/cache/markdownlint.json
            builder/cache/cspell.json
            builder/cache/schema.json